import colors

# Window Settings
WIDTH = 500
HEIGHT = 700
FPS = 60
WIN_COLOR = colors.WHITE

# Player Settings
SPACESHIP_HEIGHT = 40
SPACESHIP_WIDTH = 55
SPACESHIP_VEL = 5

# Bullet Settings
MAX_BULLETS = 5
BULLET_HEIGHT = 10
BULLET_WIDTH = 5
BULLET_VEL = 10
BULLET_COLOR = colors.RED